// @author Patrik Viklander
var DB5 = {
    "spirits"   :
        [{
            "nr": "4230201",
            "artikelid": "26473",
            "varnummer": "42302",
            "namn": "Brunello di Montalcino",
            "namn2": "Val di Suga",
            "prisinklmoms": "254.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2000-11-06",
            "slutlev": " ",
            "varugrupp": "Rött vin, Stramt & Nyanserat",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Toscana, Brunello di Montalcino",
            "ursprunglandnamn": "Italien",
            "producent": "Tenimenti Angelini",
            "leverantor": "Oenoforos AB",
            "argang": "2009",
            "provadargang": "2009",
            "alkoholhalt": "15%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "6"
        }, {
            "nr": "423302",
            "artikelid": "193327",
            "varnummer": "4233",
            "namn": "Hafner",
            "namn2": "Beerenauslese Cuvée",
            "prisinklmoms": "84.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-04-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin, Sött",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Burgenland, Neusiedlersee",
            "ursprunglandnamn": "Österrike",
            "producent": "Hafner",
            "leverantor": "Haugen-Gruppen AB",
            "argang": "2009",
            "provadargang": "2009",
            "alkoholhalt": "9.5%",
            "modul": "T9",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "7"
        }, {
            "nr": "434501",
            "artikelid": "674391",
            "varnummer": "4345",
            "namn": "Tegernseerhof",
            "namn2": "Loibenberg Riesling Smaragd",
            "prisinklmoms": "139.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-10-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Niederösterreich, Wachau",
            "ursprunglandnamn": "Österrike",
            "producent": "Tegernseerhof",
            "leverantor": "Amka Vinimport AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "10"
        }, {
            "nr": "459202",
            "artikelid": "643406",
            "varnummer": "4592",
            "namn": "Hubert Beck",
            "namn2": "Réserve du Chevalier Gewurztraminer",
            "prisinklmoms": "59.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-04-02",
            "slutlev": " ",
            "varugrupp": "Vitt vin, Torrt, Druvigt & Blo",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Hubert Beck",
            "leverantor": "Swedish Wine Cellar AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "0"
        }, {
            "nr": "524401",
            "artikelid": "189567",
            "varnummer": "5244",
            "namn": "Gustave Lorentz",
            "namn2": "Gewurztraminer Réserve",
            "prisinklmoms": "99.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-04-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Druvigt & Blommigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Gustave Lorentz",
            "leverantor": "Bibendum",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "8"
        }, {
            "nr": "8113306",
            "artikelid": "31594",
            "varnummer": "81133",
            "namn": "Heineken",
            "namn2": "",
            "prisinklmoms": "817.50",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2001-11-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Fat",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Internationellt märke",
            "producent": "Spendrups",
            "leverantor": "Spendrups Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "30"
        }, {
            "nr": "159803",
            "artikelid": "1194",
            "varnummer": "1598",
            "namn": "Corona Extra",
            "namn2": "",
            "prisinklmoms": "16.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1993-08-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Mexiko",
            "producent": "Modelo",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "65"
        }, {
            "nr": "130503",
            "artikelid": "29638",
            "varnummer": "1305",
            "namn": "Nils Oscar",
            "namn2": "God Lager",
            "prisinklmoms": "19.20",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2001-06-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Södermanlands län, Nyköpings kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Nils Oscar Company",
            "leverantor": "The Nils Oscar Company AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.3%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "22"
        }, {
            "nr": "146403",
            "artikelid": "164990",
            "varnummer": "1464",
            "namn": "Nils Oscar",
            "namn2": "India Ale",
            "prisinklmoms": "19.20",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2005-10-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Södermanlands län, Nyköpings kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Nils Oscar Company",
            "leverantor": "The Nils Oscar Company AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.3%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "26"
        }, {
            "nr": "8900203",
            "artikelid": "653568",
            "varnummer": "89002",
            "namn": "Saison",
            "namn2": "",
            "prisinklmoms": "28.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-04-02",
            "slutlev": " ",
            "varugrupp": "Öl, Specialöl",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Eskilstuna Ölkultur",
            "leverantor": "Eskilstuna Ölkultur AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "6.3%",
            "modul": "",
            "sortiment": "TSLS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "16"
        }, {
            "nr": "8900503",
            "artikelid": "541606",
            "varnummer": "89005",
            "namn": "Flying Dog Double Dog",
            "namn2": "Double Pale Ale",
            "prisinklmoms": "42.40",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2010-12-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Flying Dog Brewery",
            "leverantor": "AB Wicked Wine Sweden",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "11.5%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "20"
        }, {
            "nr": "8900603",
            "artikelid": "650516",
            "varnummer": "89006",
            "namn": "Hong Kong Dragon's Back",
            "namn2": "IPA",
            "prisinklmoms": "38.70",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-03-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Folkrepubliken Kina",
            "producent": "The Hong Kong S.A.R. Brewing C",
            "leverantor": "World Beer Trading KB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.2%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "24"
        }, {
            "nr": "8999101",
            "artikelid": "443090",
            "varnummer": "89991",
            "namn": "Leo Beer",
            "namn2": "",
            "prisinklmoms": "25.40",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2010-04-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Thailand",
            "producent": "Singha Corporation",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "6"
        }, {
            "nr": "142801",
            "artikelid": "781421",
            "varnummer": "1428",
            "namn": "Singha",
            "namn2": "",
            "prisinklmoms": "28.70",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-09-02",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Thailand",
            "producent": "Boon Rawd Brewery",
            "leverantor": "Bornicon & Salming",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "0"
        }, {
            "nr": "8484001",
            "artikelid": "819254",
            "varnummer": "84840",
            "namn": "Stetson",
            "namn2": "Straight Bourbon Whiskey",
            "prisinklmoms": "329.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-01-02",
            "slutlev": " ",
            "varugrupp": "Whisky, Bourbon",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Kentucky",
            "ursprunglandnamn": "USA",
            "producent": "John B. Stetson Spirits",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "42%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "6"
        }, {
            "nr": "1143701",
            "artikelid": "833942",
            "varnummer": "11437",
            "namn": "Grand Traverse Ole George Whiskey",
            "namn2": "",
            "prisinklmoms": "599.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-05-02",
            "slutlev": " ",
            "varugrupp": "Whisky, Rye",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Grand Traverse Distillery",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "46.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "7"
        }, {
            "nr": "1068701",
            "artikelid": "850445",
            "varnummer": "10687",
            "namn": "John Medley",
            "namn2": "Kentucky Straight Bourbon Whiskey",
            "prisinklmoms": "249.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-01",
            "slutlev": " ",
            "varugrupp": "Whisky, Bourbon",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Kentucky",
            "ursprunglandnamn": "USA",
            "producent": "John Medley",
            "leverantor": "Prime Wine Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FSN",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "4"
        }, {
            "nr": "1047601",
            "artikelid": "703109",
            "varnummer": "10476",
            "namn": "McCarthy's",
            "namn2": "Single Malt Whiskey",
            "prisinklmoms": "689.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-12-01",
            "slutlev": " ",
            "varugrupp": "Whisky, Malt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Clear Creek Distillery",
            "leverantor": "Clydesdale AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "42.5%",
            "modul": "T7",
            "sortiment": "TSE",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "5"
        }, {
            "nr": "53601",
            "artikelid": "496",
            "varnummer": "536",
            "namn": "Paddy",
            "namn2": "Old Irish Whiskey",
            "prisinklmoms": "254.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1993-01-24",
            "slutlev": " ",
            "varugrupp": "Whisky, Blended",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Irland",
            "producent": "Cork Distilleries",
            "leverantor": "Pernod Ricard Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "4"
        }, {
            "nr": "57402",
            "artikelid": "12581",
            "varnummer": "574",
            "namn": "Seagram's Seven Crown",
            "namn2": "Blended Whiskey",
            "prisinklmoms": "119.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1997-01-07",
            "slutlev": " ",
            "varugrupp": "Whisky, Blended",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Seagram",
            "leverantor": "Diageo Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "",
            "koscher": "0",
            "quantity": "0"
        }, {
            "nr": "3901",
            "artikelid": "84",
            "varnummer": "39",
            "namn": "Beefeater",
            "namn2": "London Dry Gin",
            "prisinklmoms": "70.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1993-10-01",
            "slutlev": " ",
            "varugrupp": "Gin",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Storbritannien",
            "producent": "James Burrough",
            "leverantor": "Pernod Ricard Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "special",
            "koscher": "0",
            "quantity": "6"
        }, {
            "nr": "8650404",
            "artikelid": "346896",
            "varnummer": "86504",
            "namn": "Absolut Vodka",
            "namn2": "",
            "prisinklmoms": "249.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2008-10-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Skåne län, Kristianstads kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "V&S",
            "leverantor": "Pernod Ricard Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "special": "special",
            "koscher": "0",
            "quantity": "5"
        }, {
            "nr": "9801",
            "artikelid": "176",
            "varnummer": "98",
            "namn": "Absolut Citron",
            "namn2": "",
            "prisinklmoms": "249.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1992-12-17",
            "slutlev": " ",
            "varugrupp": "Smaksatt sprit",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Skåne län, Kristianstads kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "The Absolut Company",
            "leverantor": "Pernod Ricard Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "special",
            "koscher": "0",
            "quantity": "16"
        }, {
            "nr": "8758901",
            "artikelid": "778365",
            "varnummer": "87589",
            "namn": "Del Maguey",
            "namn2": "San Jose Rio Minas",
            "prisinklmoms": "1299.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-08-01",
            "slutlev": " ",
            "varugrupp": "Tequila och Mezcal",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Mexiko",
            "producent": "Del Maguey",
            "leverantor": "Symposion International AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "48%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "1",
            "special": "special",
            "koscher": "0",
            "quantity": "10"
        }, {
            "nr": "70901",
            "artikelid": "259064",
            "varnummer": "709",
            "namn": "Fishshot",
            "namn2": "",
            "prisinklmoms": "229.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2007-04-16",
            "slutlev": " ",
            "varugrupp": "Likör, Kryddor och örter",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Internationellt märke",
            "producent": "United Drinks",
            "leverantor": "Chris-Wine AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "30%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "special": "special",
            "koscher": "0",
            "quantity": "8"
        }],

    "foods"     :
        [{
            "nr": "001",
            "artikelid": "1",
            "namn": "Hamburger with fries",
            "prisinklmoms": "120.00",
            "varugrupp": "food",
            "special": "",
            "beskrivning": "Hamburger with bacon, salad, bbq-sauce and our homemade dressing."
        }, {
            "nr": "002",
            "artikelid": "2",
            "namn": "Nachos",
            "prisinklmoms": "95.00",
            "varugrupp": "food",
            "special": "",
            "beskrivning": "Our special nachoplate together with cheese, salsa, pico de gallo and guacamole."
        }, {
            "nr": "003",
            "artikelid": "3",
            "namn": "Hot Wings",
            "prisinklmoms": "80.00",
            "varugrupp": "food",
            "special": "",
            "beskrivning": "The captains homemade hot wings served with our special chili sauce"
        }, {
            "nr": "004",
            "artikelid": "4",
            "namn": "Mozzarella sticks",
            "prisinklmoms": "65.00",
            "varugrupp": "food",
            "special": "",
            "beskrivning": "Some nice and cheesy sticks made of mozzarella cheese"
        }, {
            "nr": "005",
            "artikelid": "5",
            "namn": "Fries",
            "prisinklmoms": "35.00",
            "varugrupp": "food",
            "special": "",
            "beskrivning": "A large platter of our fries"
        }]
};